### PR TITLE
fix script errors

### LINKED ISSUE #5: npm run build/start error
I am getting errors (see below) when trying to execute `npm run build` and/or `npm run start` locally.

Do these commands work for you?

If so, did you have to do anything special to create `index.html` in `/cliams/public/` as per the error?

## npm run build
```
usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run build --scripts-prepend-node-path=auto

> claimapp@0.1.0 build /Users/anthony/Projects/cliams
> react-scripts build

Could not find a required file.
  Name: index.html
  Searched in: /Users/anthony/Projects/cliams/public
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! claimapp@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the claimapp@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anthony/.npm/_logs/2020-11-04T19_59_19_623Z-debug.log

Process finished with exit code 1
```

## npm run start
```
sr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> claimapp@0.1.0 start /Users/anthony/Projects/cliams
> react-scripts start

Could not find a required file.
  Name: index.html
  Searched in: /Users/anthony/Projects/cliams/public
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! claimapp@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the claimapp@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anthony/.npm/_logs/2020-11-04T20_00_02_741Z-debug.log

Process finished with exit code 1
```

### PR DESCRIPTION
**Pull request by brignano**
Looks like files weren't in the expected directory structure as per default react-app so I have moved them to `/public` and `/src` accordingly which resolves the npm build and run script errors that I was having.

Closes #5

### CODE REVIEW

**Comment by byAniket** [comment]
Hello Anthony,

Sorry, I though my files were posted to the repository within the public and src files. Sorry about that, not sure what really happened.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by brignano** [comment]
> Hello Anthony, Sorry, I though my files were posted to the repository within the public and src files. Sorry about that, not sure what really happened.

All good! It was a simple fix. 🔢 

If you review and approve, you can merge these code changes into your branch and the errors should go away.

The only blocker for me right now is #8; If you could provide some details there on what the API considers as a valid request body that would be helpful. 🥇 👍

**Comment by mattkoser** [comment]
I responded in #8 with some additional info

**Comment by brignano** [comment]
Closing as changes are also in #9.

**Pull request closed without merging**
